### ISSUE TITLE
Failed to launch browser process.

### ISSUE THREAD

**Issue by FireWeb1** [tegal1337/Youtube-Auto-Commenter#14]
I can't get the program to work. It always gives me this error when I try to start:

```
D:\Youtube-Auto-Commenter-main\node_modules\puppeteer\lib\cjs\puppeteer\node\BrowserRunner.js:197
            reject(new Error([
                   ^

Error: Failed to launch the browser process! spawn C:\Program Files\Google\Chrome\Application\chrome.exe ENOENT


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (D:\Youtube-Auto-Commenter-main\node_modules\puppeteer\lib\cjs\puppeteer\node\BrowserRunner.js:197:20)
    at ChildProcess.<anonymous> (D:\Youtube-Auto-Commenter-main\node_modules\puppeteer\lib\cjs\puppeteer\node\BrowserRunner.js:189:85)
    at ChildProcess.emit (node:events:537:28)
    at ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Node.js v18.4.0
```

I have installed all dependencies as far as I know.

**Comment by FireWeb1** [comment]
I fixed it by removing the line on line 32:
```
executablePath: "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe", 
```
